mode: seldonian
fixed_lambda: 1.0
seed: 42
output_dir: ./outputs
dataset_name: adult_income
sensitive_attribute: gender
behavior_policy_type: random
bandit_data_dir: ./bandit_datasets
constraint_type: students-ttest
disparity_type: reward
num_epochs: 100
batch_size: 128
param_opt_lr: 1.0e-4
dual_opt_lr: 5.0e-2
epsilon: 0.3
fail_prob: 0.05
log_lambda_max: 2
eval_freq: 25
inferred_proportion: 0.5
fpr: 0.2
fnr: 0.2
